import sys

# finds all the times when the level of fear is significant
def find_significant(scared_vals):

    significant = []
    threshhold = 10**(-3)

    for i in range(len(scared_vals)):
        if scared_vals[i] < threshhold:
            continue
        significant.append(scared_vals[i])

    return significant

# call this like
# 'python analyze.py <name> <num_of_files>'
# where
# <name> is the name of the .out files generated by emotion_api.py
# <num_of_files> is the total number of .out files (same as num_of_pics)
def genFearScores(filename, no_of_pics):
    scared_vals = [None] * no_of_pics
    for i in range(no_of_pics):
        out_name = filename + '_' + str(i) + '.out'

        with open(out_name, 'r') as f:
            val = float(f.readline().rstrip('\n'))
            scared_vals[i] = val
    return find_significant(scared_vals)
